apiVersion: v1
kind: Service
metadata:
  name: grafana-service-nodeport
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 31002  # Choose a nodePort number within the range 30000-32767

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service-nodeport
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 31001