name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t tunahanyilmaz/petclinic:latest .
        docker push tunahanyilmaz/petclinic:latest

    - name: Install kubectl
      run: |
        sudo apt-get update && sudo apt-get install -y apt-transport-https
        sudo curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
        echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
        sudo apt-get update
        sudo apt-get install -y kubectl

    - name: Set up Kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f petclinic-deployment.yaml --insecure-skip-tls-verify 
        kubectl apply -f petclinic-service.yaml --insecure-skip-tls-verify 
        kubectl apply -f postgres-deployment.yaml --insecure-skip-tls-verify 
        kubectl apply -f pv.yaml --insecure-skip-tls-verify 
        kubectl apply -f petclinic-secrets.yaml --insecure-skip-tls-verify 
        kubectl apply -f postgres-configmap.yaml --insecure-skip-tls-verify  
        kubectl apply -f postgres-secret.yaml --insecure-skip-tls-verify 
        kubectl apply -f pvc.yaml --insecure-skip-tls-verify 
