name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t tunahanyilmaz/petclinic:latest .
        docker push tunahanyilmaz/petclinic:latest

    - name: Set up Kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f petclinic-deployment.yaml --validate=false
        kubectl apply -f petclinic-service.yaml --validate=false
        kubectl apply -f postgres-deployment.yaml --validate=false
        kubectl apply -f pv.yaml --validate=false
        kubectl apply -f petclinic-secrets.yaml --validate=false
        kubectl apply -f postgres-configmap.yaml --validate=false
        kubectl apply -f postgres-secret.yaml --validate=false
        kubectl apply -f pvc.yaml --validate=false
