name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: self-hosted 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      run: |
        docker buildx create --name mybuilder --use
        docker buildx inspect --bootstrap

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Build and Push Docker image
      run: |
        IMAGE_TAG=$(echo $(date +%s) | shasum -a 256 | base64 | head -c 12 ; echo)
        docker buildx build --platform linux/amd64 --push -t tunahanyilmaz/petclinic:$IMAGE_TAG .
        echo "::set-output name=image_tag::$IMAGE_TAG"

    - name: Deploy to Kubernetes
      uses: tale/kubectl-action@v1
      with:
        base64-kube-config: ${{ secrets.KUBECONFIG }}

    - name: Apply YAML files with Kustomize
      run: |
        brew install kustomize
        kustomize build . | kubectl apply --insecure-skip-tls-verify -f -
      working-directory: ./k8s/overlays/production
  