name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: self-hosted 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2


 

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Build Docker image
      id: build-and-push   
      run: |
        # Using shasum for macOS instead of sha256sum
        IMAGE_TAG=$(echo $(date +%s) | shasum -a 256 | base64 | head -c 12 ; echo)
        docker build -t tunahanyilmaz/petclinic:$IMAGE_TAG .
        docker push tunahanyilmaz/petclinic:$IMAGE_TAG
        echo "::set-output name=image_tag::$IMAGE_TAG"
          
  
    - name: Deploy to Kubernetes
      uses: tale/kubectl-action@v1
      with:
        base64-kube-config: ${{ secrets.KUBECONFIG }}

    - name: Apply YAML files
      run: |
          cat petclinic-deployment.yaml
          sed -i "s|tunahanyilmaz/petclinic:latest|tunahanyilmaz/petclinic:${{ steps.build-and-push.outputs.image_tag }}|g" petclinic-deployment.yaml
          cat petclinic-deployment.yaml
          kubectl apply -f petclinic-deployment.yaml --insecure-skip-tls-verify 
          kubectl apply -f petclinic-service.yaml --insecure-skip-tls-verify 
          kubectl apply -f postgres-deployment.yaml --insecure-skip-tls-verify 
          kubectl apply -f pv.yaml --insecure-skip-tls-verify 
          kubectl apply -f petclinic-secrets.yaml --insecure-skip-tls-verify 
          kubectl apply -f postgres-config.yaml --insecure-skip-tls-verify  
          kubectl apply -f postgres-secret.yaml --insecure-skip-tls-verify 
          kubectl apply -f postgres-pvc.yaml --insecure-skip-tls-verify 
